apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/taski-devops-assessment/nodejs-gitops.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

